services:
  db:
    image: postgres:15
    container_name: sekurity-db
    environment:
      POSTGRES_DB: sekurity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sekurity-admin
    ports:
      - "3005:3005"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  app-user:
    build:
      context: ../sekurity-server-user
      dockerfile: Dockerfile
    container_name: sekurity-user
    ports:
      - "3006:3006"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../sekurity-server-user/.env

volumes:
  postgres_data:
